from .base_admin_change_test_case import BaseAdminChangePageTestCase
from .base_admin_list_test_case import BaseAdminListPageTestCase
from .base_admin_test_case import BaseAdminTestCase
from .base_admin_test_case_superuser_mixin import BaseAdminTestCaseSuperuserMixin
from .base_selenium_test_case import BaseSeleniumTestCase
